Feature/health check
ilanprais/tt-callofduty pull request #1
Opened 2023-02-20 13:24 UTC by ilanprais

2023-02-20 14:03 UTC, gthecht commented
`add node_modules to gitignore` and `Remove the now ignored...` should be one commit

2023-02-20 14:04 UTC, gthecht commented
add node_modules to gitignore and Remove the now ignored... should be one commit

2023-02-20 14:05 UTC, gthecht commented
The gitignores and other initialization commits should come before the code

2023-02-20 15:34 UTC, gthecht requested changes

2023-02-20 15:34 UTC, gthecht commented on .env
> +CODPORT=3000
COD_PORT

2023-02-20 15:34 UTC, gthecht commented on .env
> +CODPORT=3000
I don't see any other ports, maybe this should just be PORT

2023-02-20 15:34 UTC, gthecht commented on .env
> +LOCALMONGOURL="mongodb://127.0.0.1:27017"
- Split words with underscore
- This is in fact a URI, not a URL
- In our branch, we usually start the keyword with URI - because that way they are sorted alphabetically, and then all the URIs will be together

2023-02-20 15:34 UTC, gthecht commented on .env
> +LOCALMONGOURL="mongodb://127.0.0.1:27017"
Additionally, this is the mongo uri, doesn't have to be local right? Imaging you're deploying this elsewhere, or you decide to use mongo-atlas... what then? You'll change your code? The idea of the env is so you can control the values for tests and local runs, while it doesn't change anything in your code when you deploy

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +const app: Express = express();
express returns the type Express, so even if you write
```TS
const app = express();
```
It'll make the app be of type Express (check it out by hovering over app)

That way you can remove the import which is a win because its ugly how you did it!

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +const routes = require("./controllers/server");
Don't use both import and require together. Since you went with import, import local files as well

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +  next();
Why have you decided to use callbacks?

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +app.use((req, res, next) => {
Why did you add a logger?
If you want a logger, I suggest looking for an existing middleware... And not writing a callback one

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +  const localMongoUrl: string | undefined = process.env.LOCALMONGOURL;
Again, you just copied the type from what it told you. No need. It'll know.

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +  const localMongoUrl: string | undefined = process.env.LOCALMONGOURL;
Why is this the local mongo? Change this in every relevant location...

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +    await mongoose.connect(
one line:
```TS
await mongoose.connect(mongoURI);
```

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +    app.listen(process.env.CODPORT, () => console.log("Server started on port " + process.env.CODPORT));
Can this fail? Why is it in the try?

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +const start = async () => {
You are doing to things in this function:
1. Connecting to mongo (but you aren't using it anywhere)
2. starting the app

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +start();
I prefer exporting the start function, and having it return the server...

2023-02-20 15:34 UTC, gthecht commented on package.json
> +    "test": "mocha --require ts-node/register tests/*.ts"
Are you going to use mocha or jest? and are you sure you need all these other stuff? I don't know about them, but haven't used mocha with TS

2023-02-20 15:34 UTC, gthecht commented on package.json
> +    "eslint": "^8.34.0"
this is a dev-dependency

2023-02-20 15:34 UTC, gthecht commented on package.json
> +  "dependencies": {
Where's express?

2023-02-20 15:34 UTC, gthecht commented on controllers/server.ts
> +module.exports = router;
use the modular nodejs:
```JS
export default router
```

2023-02-20 15:34 UTC, gthecht commented on controllers/server.ts
> +module.exports = router;
Where do the app and the router meet each other? They are currently separate

2023-02-20 15:34 UTC, gthecht commented on tests/server.test.ts
> +});
Add an empty line at the end (linter)

2023-02-20 15:34 UTC, gthecht commented on tests/server.test.ts
> +import "mocha";
use jest

2023-02-20 15:34 UTC, gthecht commented on tests/server.test.ts
> +import chai from "chai";
jest

2023-02-20 15:34 UTC, gthecht commented on tests/server.test.ts
> +import chaiHttp from "chai-http";
use supertest

2023-02-20 15:34 UTC, gthecht commented on app.ts
> +const start = async () => {
And btw you aren't supposed to have any mongo in this first branch, so put it in a separate branch and connect it there

2023-02-20 18:13 UTC, Nimtso commented on .gitignore
> +node_modules
What about the build from typescript ?

2023-02-20 18:13 UTC, Nimtso commented on app.ts
> +app.use((req, res, next) => {
What is the type ?

2023-02-22 08:49 UTC, Nimtso commented on app.ts
> +  console.log(`${new Date().toLocaleString()}: recieved request to route ${req.url}`);
Wrap a logger. Also, look to middleware

2023-02-22 08:49 UTC, Nimtso commented on app.ts
> +  const localMongoUrl: string | undefined = process.env.LOCALMONGOURL;
Look at validating your configuration all at once and removing all the `undefined`

2023-02-22 08:49 UTC, Nimtso commented on app.ts
> +export {app};
`export { app }`

2023-02-22 08:49 UTC, Nimtso commented on app.ts
> +import {router as routes} from "./controllers/server"
extraneous imports and only then inside modules

2023-02-22 08:49 UTC, Nimtso commented on app.ts
> +    app.listen(process.env.PORT, () => console.log("Server started on port " + process.env.PORT));
What about validating your configuration ?

2023-02-22 08:49 UTC, Nimtso commented on app.ts
> +    app.listen(process.env.PORT, () => console.log("Server started on port " + process.env.PORT));
Wrap console with a logger

2023-02-22 08:49 UTC, Nimtso commented on app.ts
> +    app.listen(process.env.PORT, () => console.log("Server started on port " + process.env.PORT));
BTW,
Either `console.log("Server started on port ", process.env.PORT)` with a comma
or use `Server started on ${PORT}

2023-02-22 08:49 UTC, Nimtso commented on app.ts
> +export {start};
Export the app and then use it in a file called index to start the app

2023-02-22 08:49 UTC, Nimtso commented on app.ts
> +  } catch (error: any) {
Any ?????

2023-02-22 08:49 UTC, Nimtso commented on package.json
> +    "supertest": "^6.3.3",
dev

2023-02-22 08:49 UTC, Nimtso commented on package.json
> +    "ts-jest": "^29.0.5"
dev

2023-02-22 08:49 UTC, Nimtso commented on package.json
> +    "@types/supertest": "^2.0.12",
dev

2023-02-22 08:49 UTC, Nimtso commented on controllers/server.ts
> +export {router};
Is this linted ? `export { router }`

2023-02-22 14:43 UTC, gthecht approved these changes
Overall its good,
just a few small fixes, and then you can merge.

I want start and build scripts and to be able to run them on my computer, so just make sure they are there in the next branch or this one - whichever you prefer.

2023-02-22 14:43 UTC, gthecht commented on app.ts
> +
you can remove this empty line

2023-02-22 14:43 UTC, gthecht commented on app.ts
> +import {router as routes} from "./controllers/server"
spaces between braces:
```js
{ router: routes }
```

2023-02-22 14:43 UTC, gthecht commented on app.ts
> +import {router as routes} from "./controllers/server"
./controllers/server.js

2023-02-22 14:43 UTC, gthecht commented on app.ts
> +    console.error(error);
Won't this simply happen from if you don't catch the error?

2023-02-22 14:43 UTC, gthecht commented on app.ts
> +    console.error(error);
Including the process.exit

2023-02-22 14:43 UTC, gthecht commented on controllers/server.ts
> +router.get("/", (req: Request, res: Response) => {
what is this route for?

2023-02-22 14:43 UTC, gthecht commented on package.json
> +    "dev": "nodemon app.ts"
you need a start script and a build script. I want to run and see that it works

2023-02-22 15:10 UTC, closed without merging